# password
CALL createUser('admin', '$2b$10$MkCIstzWubxkWw4c9F6n6.wuu4JHRHARPhgwdL0X6XArPz6BSFAY6', NULL, '2000-01-01', 'male');
# test
CALL createUser('test', '$2b$10$/Um7c/QUKWsZmuifiNoJL.hCaPaK0R5Pu.SCrDG7KXmdT9BleAjB.', NULL, '2000-01-01', 'male');


CALL createTag('Single Ingredient', 'Drink');
CALL createTag('Non-Alcoholic', 'Drink');
CALL createTag('Shot', 'Drink');
CALL createTag('Spirit & Mixer', 'Drink');
CALL createTag('Cocktail', 'Drink');
CALL createTag('Shaken', 'Drink');
CALL createTag('Stirred', 'Drink');
CALL createTag('Invalid', 'Drink');

CALL createTag('Non-Alcoholic', 'Ingredient');
CALL createTag('Spirit', 'Ingredient');
CALL createTag('Liqueur', 'Ingredient');
CALL createTag('Wine', 'Ingredient');
CALL createTag('Carbonated', 'Ingredient');
CALL createTag('Sugar Free', 'Ingredient');
CALL createTag('Invalid', 'Ingredient');

CALL createIngredientTemp('Other', 0, 0, 'Invalid', 1, NULL, NULL);
CALL createIngredientTemp('Red Wine', 14, 0.7, 'Wine', 1, NULL, NULL);
CALL createIngredientTemp('White Wine', 14, 1, 'Wine', 1, NULL, NULL);
CALL createIngredientTemp('Champagne', 13, 1, 'Wine, Carbonated', 1, NULL, NULL);
CALL createIngredientTemp('Vodka', 40, 0, 'Spirit, Sugar Free', 1, NULL, NULL);
CALL createIngredientTemp('Gin', 40, 0, 'Spirit, Sugar Free', 1, NULL, NULL);
CALL createIngredientTemp('Rum', 40, 0, 'Spirit, Sugar Free', 1, NULL, NULL);
CALL createIngredientTemp('Whiskey', 40, 0, 'Spirit, Sugar Free', 1, NULL, NULL);
CALL createIngredientTemp('Tequila', 40, 0, 'Spirit, Sugar Free', 1, NULL, NULL);
CALL createIngredientTemp('Cognac', 40, 1.5, 'Spirit, Sugar Free', 1, NULL, NULL);
CALL createIngredientTemp('Armagnac', 40, 0, 'Spirit', 1, NULL, NULL);
CALL createIngredientTemp('Mezcal', 40, 0, 'Spirit, Sugar Free', 1, NULL, NULL);
CALL createIngredientTemp('Green Chartreuse', 55, 26, 'Liqueur', 1, NULL, NULL);
CALL createIngredientTemp('Yellow Chartreuse', 40, 31.2, 'Liqueur', 1, NULL, NULL);
CALL createIngredientTemp('Cointreau', 40, 23, 'Spirit', 1, NULL, NULL);
CALL createIngredientTemp('Luxardo Maraschino Liqueur', 32, 35, 'Liqueur', 1, NULL, NULL);
CALL createIngredientTemp('Campari', 25, 24, 'Liqueur', 1, NULL, NULL);
CALL createIngredientTemp('Sweet Vermouth', 15, 16, 'Wine', 1, NULL, NULL);
CALL createIngredientTemp('Dry Vermouth', 15, 3, 'Wine', 1, NULL, NULL);
CALL createIngredientTemp('Jagermeister', 35, 13.2, 'Liqueur', 1, NULL, NULL);
CALL createIngredientTemp('Absinthe', 60, 0, 'Spirit', 1, NULL, NULL);
CALL createIngredientTemp('Beer', 5, 0, 'Carbonated', 1, NULL, NULL);
CALL createIngredientTemp('Cider', 5, 5, 'Carbonated', 1, NULL, NULL);
CALL createIngredientTemp('Alize', 16, 20, 'Liqueur', 1, NULL, NULL);
CALL createIngredientTemp('Soju', 15, 5, 'Spirit', 1, NULL, NULL);
CALL createIngredientTemp('Sake', 15, 0, 'Spirit, Sugar Free', 1, NULL, NULL);
CALL createIngredientTemp('Lemon Juice', 0, 1.6, 'Non-Alcoholic', 1, NULL, NULL);
CALL createIngredientTemp('Lime Juice', 0, 1.6, 'Non-Alcoholic', 1, NULL, NULL);
CALL createIngredientTemp('Simple Syrup', 0, 61.5, 'Non-Alcoholic', 1, NULL, NULL);
CALL createIngredientTemp('Soda Water', 0, 0, 'Non-Alcoholic, Sugar Free, Carbonated', 1, NULL, NULL);
CALL createIngredientTemp('Lemonade', 0, 10.8, 'Non-Alcoholic, Carbonated', 1, NULL, NULL);
CALL createIngredientTemp('Lemonade (No Sugar)', 0, 0, 'Non-Alcoholic, Sugar Free, Carbonated', 1, NULL, NULL);
CALL createIngredientTemp('Coke', 0, 10.6, 'Non-Alcoholic, Carbonated', 1, NULL, NULL);
CALL createIngredientTemp('Coke (No Sugar)', 0, 0, 'Non-Alcoholic, Carbonated, Sugar Free', 1, NULL, NULL);
CALL createIngredientTemp('Red Bull', 0, 11, 'Non-Alcoholic, Carbonated', 1, NULL, NULL);
CALL createIngredientTemp('Tonic Water', 0, 7.1, 'Non-Alcoholic, Carbonated', 1, NULL, NULL);
CALL createIngredientTemp('Water', 0, 0, 'Non-Alcoholic, Sugar Free', 1, NULL, NULL);



CALL parseDrinkTemp(1, 'Daiquiri', 'Cocktail', 'Rum,60.00,Lime Juice,22.50,Simple Syrup,22.50');
CALL parseDrinkTemp(1, 'Margarita', 'Cocktail', 'Tequila,60.00,Cointreau,30.00,Lime Juice,30.00');
CALL parseDrinkTemp(1, 'Negroni', 'Cocktail', 'Gin,30.00,Campari,30.00,Sweet Vermouth,30.00');
CALL parseDrinkTemp(1, 'Martini', 'Cocktail', 'Gin,60.00,Dry Vermouth,15.00');
CALL parseDrinkTemp(1, 'Jagerbomb', 'Spirit & Mixer', 'Jagermeister,30.00,Red Bull,120.00');
CALL parseDrinkTemp(1, 'Vodka Lemonade', 'Spirit & Mixer', 'Vodka,30.00,Lemonade,120.00');
CALL parseDrinkTemp(1, 'Rum and Coke', 'Spirit & Mixer', 'Rum,30.00,Coke,120.00');
CALL parseDrinkTemp(1, 'Whiskey and Coke', 'Spirit & Mixer', 'Whiskey,30.00,Coke,120.00');
CALL parseDrinkTemp(1, 'Gin and Tonic', 'Spirit & Mixer', 'Gin,30.00,Tonic Water,120.00');
CALL parseDrinkTemp(1, 'Alize Lemonade', 'Spirit & Mixer', 'Alize,30.00,Lemonade,120.00');
CALL parseDrinkTemp(1, 'Mojito', 'Cocktail', 'Rum,60.00,Lime Juice,22.50,Simple Syrup,22.50,Soda Water,90.00');
CALL parseDrinkTemp(1, 'Sidecar', 'Cocktail', 'Cognac,30.00,Cointreau,30.00,Lemon Juice,30.00');
CALL parseDrinkTemp(1, 'Soju bottle', 'Single Ingredient', 'Soju,360.00');
CALL parseDrinkTemp(1, 'Red wine (small glass);', 'Single Ingredient', 'Red Wine,150.00');
CALL parseDrinkTemp(1, 'Red wine (medium glass);', 'Single Ingredient', 'Red Wine,200.00');
CALL parseDrinkTemp(1, 'Red wine (large glass);', 'Single Ingredient', 'Red Wine,250.00');
CALL parseDrinkTemp(1, 'White wine (small glass);', 'Single Ingredient', 'White Wine,150.00');
CALL parseDrinkTemp(1, 'White wine (medium glass);', 'Single Ingredient', 'White Wine,200.00');
CALL parseDrinkTemp(1, 'White wine (large glass);', 'Single Ingredient', 'White Wine,250.00');
CALL parseDrinkTemp(1, 'Vodka shot', 'Single Ingredient,Shot', 'Vodka,30.00');
CALL parseDrinkTemp(1, 'Gin shot', 'Single Ingredient,Shot', 'Gin,30.00');
CALL parseDrinkTemp(1, 'Rum shot', 'Single Ingredient,Shot', 'Rum,30.00');
CALL parseDrinkTemp(1, 'Whiskey shot', 'Single Ingredient,Shot', 'Whiskey,30.00');
CALL parseDrinkTemp(1, 'Tequila shot', 'Single Ingredient,Shot', 'Tequila,30.00');
CALL parseDrinkTemp(1, 'Cognac shot', 'Single Ingredient,Shot', 'Cognac,30.00');
CALL parseDrinkTemp(1, 'Armagnac shot', 'Single Ingredient,Shot', 'Armagnac,30.00');
CALL parseDrinkTemp(1, 'Mezcal shot', 'Single Ingredient,Shot', 'Mezcal,30.00');
CALL parseDrinkTemp(1, 'Green Chartreuse shot', 'Single Ingredient,Shot', 'Green Chartreuse,30.00');
CALL parseDrinkTemp(1, 'Yellow Chartreuse shot', 'Single Ingredient,Shot', 'Yellow Chartreuse,30.00');
CALL parseDrinkTemp(1, 'Cointreau shot', 'Single Ingredient,Shot', 'Cointreau,30.00');
CALL parseDrinkTemp(1, 'Luxardo Maraschino Liqueur shot', 'Single Ingredient,Shot', 'Luxardo Maraschino Liqueur,30.00');
CALL parseDrinkTemp(1, 'Campari shot', 'Single Ingredient,Shot', 'Campari,30.00');
CALL parseDrinkTemp(1, 'Jagermeister shot', 'Single Ingredient,Shot', 'Jagermeister,30.00');
CALL parseDrinkTemp(1, 'Absinthe shot', 'Single Ingredient,Shot', 'Absinthe,30.00');
CALL parseDrinkTemp(1, 'Alize shot', 'Single Ingredient,Shot', 'Alize,30.00');
CALL parseDrinkTemp(1, 'Soju shot', 'Single Ingredient,Shot', 'Soju,30.00');
CALL parseDrinkTemp(1, 'Sake shot', 'Single Ingredient,Shot', 'Sake,30.00');
CALL parseDrinkTemp(1, 'Vodka shooter', 'Single Ingredient,Shot', 'Vodka,60.00');
CALL parseDrinkTemp(1, 'Gin shooter', 'Single Ingredient,Shot', 'Gin,60.00');
CALL parseDrinkTemp(1, 'Rum shooter', 'Single Ingredient,Shot', 'Rum,60.00');
CALL parseDrinkTemp(1, 'Whiskey shooter', 'Single Ingredient,Shot', 'Whiskey,60.00');
CALL parseDrinkTemp(1, 'Tequila shooter', 'Single Ingredient,Shot', 'Tequila,60.00');
CALL parseDrinkTemp(1, 'Cognac shooter', 'Single Ingredient,Shot', 'Cognac,60.00');
CALL parseDrinkTemp(1, 'Armagnac shooter', 'Single Ingredient,Shot', 'Armagnac,60.00');
CALL parseDrinkTemp(1, 'Mezcal shooter', 'Single Ingredient,Shot', 'Mezcal,60.00');
CALL parseDrinkTemp(1, 'Green Chartreuse shooter', 'Single Ingredient,Shot', 'Green Chartreuse,60.00');
CALL parseDrinkTemp(1, 'Yellow Chartreuse shooter', 'Single Ingredient,Shot', 'Yellow Chartreuse,60.00');
CALL parseDrinkTemp(1, 'Cointreau shooter', 'Single Ingredient,Shot', 'Cointreau,60.00');
CALL parseDrinkTemp(1, 'Luxardo Maraschino Liqueur shooter', 'Single Ingredient,Shot', 'Luxardo Maraschino Liqueur,60.00');
CALL parseDrinkTemp(1, 'Campari shooter', 'Single Ingredient,Shot', 'Campari,60.00');
CALL parseDrinkTemp(1, 'Jagermeister shooter', 'Single Ingredient,Shot', 'Jagermeister,60.00');
CALL parseDrinkTemp(1, 'Absinthe shooter', 'Single Ingredient,Shot', 'Absinthe,60.00');
CALL parseDrinkTemp(1, 'Alize shooter', 'Single Ingredient,Shot', 'Alize,60.00');
CALL parseDrinkTemp(1, 'Soju shooter', 'Single Ingredient,Shot', 'Soju,60.00');
CALL parseDrinkTemp(1, 'Sake shooter', 'Single Ingredient,Shot', 'Sake,60.00');

